[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "YT-Advanced/ReX-patches"
#integrations-source = "YT-Advanced/ReX-integrations"
integrations-source = "inotia00/ReX-integrations"
#cli-source = "YT-Advanced/revanced-cli"
cli-source = "/revanced-cli"
cli-source = "inotia00/revanced-cli"
rv-brand = "Advanced"
#apkmirror-arch = "arm64-v8a"
version = "18.34.37"
included-patches = "materialyou theme force-vp9-codec force-premium-heading optimize-resource"
excluded-patches = "sponsorblock return-youtube-dislike bypass-ambient-mode-restrictions layout-switch custom-video-speed custom-branding-icon-mmt custom-branding-icon-revancify-blue custom-branding-icon-revancify-red custom-branding-youtube-name custom-package-name hide-my-mix nable-hdr-auto-brightnes enable-wide-searchbar translations"


[Twitter]
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitter-inc/twitter/"
rv-brand = "Revanced"
